foundation = '$SDKROOT/System/Library/Frameworks/Foundation.framework'
xctest = '$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework'

apple_library(
  name = 'StaticLib',

  exported_headers = glob(['StaticLib/*.h']),
  srcs = glob(['StaticLib/*.m']),
  frameworks = [foundation],
  preprocessor_flags = ['-fobjc-arc'],
  tests = [':StaticLibTests'],
)

apple_test(
  name = 'StaticLibTests',

  srcs = glob(['StaticLibTests/*.m']),

  # dependencies
  deps = [
    ':StaticLib', 
    '//ThirdParty/OCMock:OCMock',
  ],
  frameworks = [foundation, xctest],
  libraries = ['Libs/libOCMock.a'],

  # config
  linker_flags = ['-ObjC'],
  preprocessor_flags = ['-fobjc-arc'],
  info_plist = 'StaticLibTests/Info.plist',
)
